services:
  backend:
    container_name: shop_backend
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    container_name: shop_frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: shop_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: market_pass
      POSTGRES_DB: market_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d  # SQL скрипты для инициализации
  volumes:
    db_data: