#!/bin/bash
set -e  # Прерывать скрипт при ошибках

# Создание ролей и пользователей
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE client WITH
        NOLOGIN
        NOSUPERUSER
        NOCREATEDB
        NOCREATEROLE;

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO client;
    GRANT USAGE ON SCHEMA public TO client;
    GRANT SELECT ON TABLE items TO client;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO client;

    CREATE USER ${DB_CLIENT_USER} WITH 
        PASSWORD '${DB_CLIENT_PASSWORD}'
        INHERIT; 

    GRANT client TO ${DB_CLIENT_USER};

    CREATE ROLE ${DB_ADMIN_SHOP} WITH
        NOLOGIN
        CREATEDB
        CREATEROLE;

    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO ${DB_ADMIN_SHOP};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_ADMIN_SHOP};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_ADMIN_SHOP};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_ADMIN_SHOP};

    CREATE USER ${DB_ADMIN_SHOP_USER} WITH 
        PASSWORD '${DB_ADMIN_SHOP_PASSWORD}'
        INHERIT;

    GRANT ${DB_ADMIN_SHOP} TO ${DB_ADMIN_SHOP_USER};
EOSQL

echo "Роли и пользователи базы данных успешно созданы!"